# Generated by Django 3.2.18 on 2023-03-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='lalla', max_length=50, verbose_name='Ingredient'),
            preserve_default=False,
        ),
    ]
