# Generated by Django 3.2.18 on 2023-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reviews',
            field=models.ManyToManyField(to='core.Review', verbose_name='Reviews'),
        ),
    ]
